apiVersion: v1
entries:
  frp-operator:
  - apiVersion: v2
    appVersion: 0.5.0
    created: "2025-12-31T21:09:10.49001+07:00"
    description: Expose your service in Kubernetes to the Internet with open source
      FRP!
    digest: 7726777bb17bd18c9f9685347b79b43b56ba5ad5504ec472ea5fe51292a3eb2c
    home: https://github.com/zufardhiyaulhaq/frp-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: frp-operator
    type: application
    urls:
    - frp-operator-1.3.0.tgz
    version: 1.3.0
  - apiVersion: v2
    appVersion: 0.4.0
    created: "2025-12-31T21:09:10.489506+07:00"
    description: Expose your service in Kubernetes to the Internet with open source
      FRP!
    digest: 13d93b94339cb9dba36ad832c204b63736480cd1a1bdeec2cc6cd4571a947daa
    home: https://github.com/zufardhiyaulhaq/frp-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: frp-operator
    type: application
    urls:
    - frp-operator-1.2.0.tgz
    version: 1.2.0
  - apiVersion: v2
    appVersion: 0.3.0
    created: "2025-12-31T21:09:10.489227+07:00"
    description: Expose your service in Kubernetes to the Internet with open source
      FRP!
    digest: 96f342725e362414480ad385e0ad6db348754e8e3bf5db0d9a7e74ee9c5905a7
    home: https://github.com/zufardhiyaulhaq/frp-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: frp-operator
    type: application
    urls:
    - frp-operator-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v2
    appVersion: 0.2.0
    created: "2025-12-31T21:09:10.488776+07:00"
    description: Expose your service in Kubernetes to the Internet with open source
      FRP!
    digest: 5f80631b3ce1dad5ed2039abb144506fa5795d378f4d465d33c475f216b77df1
    home: https://github.com/zufardhiyaulhaq/frp-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: frp-operator
    type: application
    urls:
    - frp-operator-1.0.0.tgz
    version: 1.0.0
generated: "2025-12-31T21:09:10.48821+07:00"
