apiVersion: v1
entries:
  frp-operator:
  - apiVersion: v2
    appVersion: 0.5.0
    created: "2025-12-31T12:40:15.676342+07:00"
    description: Expose your service in Kubernetes to the Internet with open source
      FRP!
    digest: f73d79ebf9734f0796cc26a2fca73f1c76fb73eeb737f4e78d154469361f2cb3
    home: https://github.com/zufardhiyaulhaq/frp-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: frp-operator
    type: application
    urls:
    - frp-operator-1.3.0.tgz
    version: 1.3.0
  - apiVersion: v2
    appVersion: 0.5.0
    created: "2025-12-31T12:40:15.675941+07:00"
    description: Expose your service in Kubernetes to the Internet with open source
      FRP!
    digest: 7a98c85ae97ff0a2d014ebf64677b6731358ff728feb9641469499d73179b5eb
    home: https://github.com/zufardhiyaulhaq/frp-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: frp-operator
    type: application
    urls:
    - frp-operator-1.2.0.tgz
    version: 1.2.0
  - apiVersion: v2
    appVersion: 0.3.0
    created: "2025-12-31T12:40:15.675705+07:00"
    description: Expose your service in Kubernetes to the Internet with open source
      FRP!
    digest: 96f342725e362414480ad385e0ad6db348754e8e3bf5db0d9a7e74ee9c5905a7
    home: https://github.com/zufardhiyaulhaq/frp-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: frp-operator
    type: application
    urls:
    - frp-operator-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v2
    appVersion: 0.2.0
    created: "2025-12-31T12:40:15.675442+07:00"
    description: Expose your service in Kubernetes to the Internet with open source
      FRP!
    digest: 5f80631b3ce1dad5ed2039abb144506fa5795d378f4d465d33c475f216b77df1
    home: https://github.com/zufardhiyaulhaq/frp-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: frp-operator
    type: application
    urls:
    - frp-operator-1.0.0.tgz
    version: 1.0.0
generated: "2025-12-31T12:40:15.674854+07:00"
