---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: clients.frp.zufardhiyaulhaq.com
spec:
  group: frp.zufardhiyaulhaq.com
  names:
    kind: Client
    listKind: ClientList
    plural: clients
    singular: client
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Client is the Schema for the clients API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ClientSpec defines the desired state of Client
            properties:
              server:
                properties:
                  authentication:
                    properties:
                      token:
                        properties:
                          secret:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        required:
                        - secret
                        type: object
                    required:
                    - token
                    type: object
                  host:
                    type: string
                  port:
                    type: integer
                required:
                - authentication
                - host
                - port
                type: object
            required:
            - server
            type: object
          status:
            description: ClientStatus defines the observed state of Client
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: upstreams.frp.zufardhiyaulhaq.com
spec:
  group: frp.zufardhiyaulhaq.com
  names:
    kind: Upstream
    listKind: UpstreamList
    plural: upstreams
    singular: upstream
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Upstream is the Schema for the upstreams API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: UpstreamSpec defines the desired state of Upstream
            properties:
              client:
                type: string
              tcp:
                properties:
                  healthCheck:
                    properties:
                      intervalSeconds:
                        type: integer
                      maxFailed:
                        type: integer
                      timeoutSeconds:
                        type: integer
                    required:
                    - intervalSeconds
                    - maxFailed
                    - timeoutSeconds
                    type: object
                  host:
                    type: string
                  port:
                    type: integer
                  proxyProtocol:
                    enum:
                    - v1
                    - v2
                    type: string
                  server:
                    properties:
                      port:
                        type: integer
                    required:
                    - port
                    type: object
                required:
                - healthCheck
                - host
                - port
                - server
                type: object
              udp:
                properties:
                  host:
                    type: string
                  port:
                    type: integer
                  server:
                    properties:
                      port:
                        type: integer
                    required:
                    - port
                    type: object
                required:
                - host
                - port
                - server
                type: object
            required:
            - client
            - tcp
            - udp
            type: object
          status:
            description: UpstreamStatus defines the observed state of Upstream
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
