---
apiVersion: v2
name: frp-operator
description: Expose your service in Kubernetes to the Internet with open source FRP!
version: 1.2.0
appVersion: 0.4.0
type: application
home: https://github.com/zufardhiyaulhaq/frp-operator

maintainers:
- name: Zufar Dhiyaulhaq
  email: zufardhiyaulhaq@gmail.com
  url: https://zufardhiyaulhaq.com
