---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.5
  name: upstreams.frp.zufardhiyaulhaq.com
spec:
  group: frp.zufardhiyaulhaq.com
  names:
    kind: Upstream
    listKind: UpstreamList
    plural: upstreams
    singular: upstream
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Upstream is the Schema for the upstreams API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: UpstreamSpec defines the desired state of Upstream
            properties:
              client:
                type: string
              tcp:
                properties:
                  healthCheck:
                    properties:
                      intervalSeconds:
                        type: integer
                      maxFailed:
                        type: integer
                      timeoutSeconds:
                        type: integer
                    required:
                    - intervalSeconds
                    - maxFailed
                    - timeoutSeconds
                    type: object
                  host:
                    type: string
                  port:
                    type: integer
                  proxyProtocol:
                    enum:
                    - v1
                    - v2
                    type: string
                  server:
                    properties:
                      port:
                        type: integer
                    required:
                    - port
                    type: object
                  transport:
                    properties:
                      bandwidthLimit:
                        properties:
                          enabled:
                            default: false
                            type: boolean
                          limit:
                            type: integer
                          type:
                            enum:
                            - KB
                            - MB
                            type: string
                        required:
                        - enabled
                        - limit
                        - type
                        type: object
                      useCompression:
                        default: false
                        type: boolean
                      useEncryption:
                        default: true
                        type: boolean
                    required:
                    - useCompression
                    - useEncryption
                    type: object
                required:
                - host
                - port
                - server
                type: object
              udp:
                properties:
                  host:
                    type: string
                  port:
                    type: integer
                  server:
                    properties:
                      port:
                        type: integer
                    required:
                    - port
                    type: object
                required:
                - host
                - port
                - server
                type: object
            required:
            - client
            type: object
          status:
            description: UpstreamStatus defines the observed state of Upstream
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
